apiVersion: v1
kind: Service
metadata:
  name: templ-demo-service
  namespace: default
  labels:
    namespace: default
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    app: templ-demo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: templ-demo
  namespace: default
  labels:
    name: templ-demo
    namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: templ-demo
  template:
    metadata:
      labels:
        app: templ-demo
    spec:
      containers:
        - name: templ-demo
          image: willdot/templ-demo
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
